SELECT 
    VENDAS.ID_VENDEDOR, 
    VENDEDORES.NOME,
    SUM(VENDAS.QTD_VENDIDA) AS [TOTA DE VENDAS]
FROM VENDAS INNER JOIN VENDEDORES
ON VENDAS.ID_VENDEDOR = VENDEDORES.ID
GROUP BY VENDAS.ID_VENDEDOR;

SELECT
    VENDAS.ID_LIVRO 
    LIVROS.NOME,
    VENDAS.QTD_VENDIDA,
FROM LIVROS LEFT JOIN VENDAS
ON LIVROS.ID = VENDAS.ID_LIVRO
;