CREATE TABLE LIVROS(
    ID INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    AUTOR VARCHAR(100) NOT NULL,
    EDITORA VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(100) NOT NULL,
    PREÇO DECIMAL(5,2) NOT NULL
    PRIMARY KEY (ID)
);

CREATE TABLE ESTOQUE (
    ID INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE VENDAS (
    ID_PEDIDO INT NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    ID_LIVRO INT NOT NULL,
    QTD_VENDIDA INT NOT NULL,
    DATA_VENDA DATE NOT NULL,
 PRIMARY KEY (ID_VENDEDOR,ID_PEDIDO)
);

CREATE TABLE VENDEDORES (
    ID INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);